### ISSUE TITLE
/var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/request.js:31

### ISSUE THREAD

**Issue by sanat1772** [dnavarrom/grafana-aws-cost-explorer-backend#4]
throw err;
            ^

TypeError: Cannot read property 'Amount' of undefined
    at /var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/index.js:145:60
    at Array.forEach (<anonymous>)
    at buildResultTimeSeries (/var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/index.js:143:35)
    at /var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/index.js:191:23
    at /var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/index.js:96:12
    at /var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/lib/dataStore.js:50:32
    at Response.<anonymous> (/var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/node_modules/aws-cost-explorer/lib/CostExplorer.js:124:20)
    at Request.<anonymous> (/var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/lib/grafana/plugins/grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

Error throws up when simultaneously loading.

**Comment by thespamer** [comment]
grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'Amount' of undefined
    at /Users/juliano/git/grafana-aws-cost-explorer-backend/index.js:145:60
    at Array.forEach (<anonymous>)
    at buildResultTimeSeries (/Users/juliano/git/grafana-aws-cost-explorer-backend/index.js:143:35)
    at /Users/juliano/git/grafana-aws-cost-explorer-backend/index.js:191:23
    at /Users/juliano/git/grafana-aws-cost-explorer-backend/index.js:96:12
    at /Users/juliano/git/grafana-aws-cost-explorer-backend/lib/dataStore.js:63:32
    at Response.<anonymous> (/Users/juliano/git/grafana-aws-cost-explorer-backend/node_modules/aws-cost-explorer/lib/CostExplorer.js:183:20)
    at Request.<anonymous> (/Users/juliano/git/grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/juliano/git/grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/juliano/git/grafana-aws-cost-explorer-backend/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    
    tested with v10.24.1 and v12.22.7 without success

**Comment by edusantos01** [comment]
C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

Error [TypeError]: Cannot read properties of undefined (reading 'Amount')
    at C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\index.js:127:60
    at Array.forEach (<anonymous>)
    at buildResultTable (C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\index.js:123:35)
    at C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\index.js:189:23
    at C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\index.js:96:12
    at C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\lib\dataStore.js:50:32
    at Response.<anonymous> (C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\node_modules\aws-cost-explorer\lib\CostExplorer.js:141:20)
    at Request.<anonymous> (C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\node_modules\aws-sdk\lib\request.js:364:18)
    at Request.callListeners (C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\Jennifer Freitas\grafana-aws-cost-explorer-backend\node_modules\aws-sdk\lib\sequential_executor.js:77:10) {
  code: 'TypeError',
  time: 2021-11-25T14:28:49.965Z
}
